### ISSUE TITLE
Can't convert the KEPLER correctly

### ISSUE THREAD

**Issue by Jajison** [THU-KEG/KEPLER#22]
i can't convert the pretrained KEPLER model(you provide) to HuggingFace's Transformers using fairseq=0.9.0 and transformers=2.2.2, because [this code](https://github.com/huggingface/transformers/blob/main/src/transformers/models/roberta/convert_roberta_original_pytorch_checkpoint_to_pytorch.py) seems to be based on another new version. 

1. Actually i've try convert_roberta_checkpoint_to_pytorch.py of transformers=2.2.2 with transformers=2.2.2, but i get "shape doesn't match" at a linear layer of decoder. 

2. And i've try [this code](https://github.com/huggingface/transformers/blob/main/src/transformers/models/roberta/convert_roberta_original_pytorch_checkpoint_to_pytorch.py) with transformers=4.7.0, and i get something as followings
`
Traceback (most recent call last):
  File "convert_kepler.py", line 177, in <module>
    args.roberta_checkpoint_path, args.pytorch_dump_folder_path, args.classification_head
  File "convert_kepler.py", line 54, in convert_roberta_checkpoint_to_pytorch
    roberta = FairseqRobertaModel.from_pretrained(roberta_checkpoint_path)
  File "/data/JiangZhiShu/miniconda3/envs/KEPLER/lib/python3.7/site-packages/fairseq/models/roberta/model.py", line 144, in from_pretrained
    **kwargs,
  File "/data/JiangZhiShu/miniconda3/envs/KEPLER/lib/python3.7/site-packages/fairseq/hub_utils.py", line 68, in from_pretrained
    arg_overrides=kwargs,
  File "/data/JiangZhiShu/miniconda3/envs/KEPLER/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 190, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/data/JiangZhiShu/miniconda3/envs/KEPLER/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 166, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/data/JiangZhiShu/miniconda3/envs/KEPLER/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 349, in _upgrade_state_dict
    registry.set_defaults(state["args"], tasks.TASK_REGISTRY[state["args"].task])
KeyError: 'MLMetKE'
`

So i want to know how to convert the pretrained KEPLER model correctly. Is this a version issue or something else?

**Comment by Bakser** [comment]
Hi, I just tried again. The command provided in our README works well on `transformers=2.2.2`. I note that you mentioned `fairseq=0.9.0`. You need to use the fairseq provided in this repo since the official faiseq does not contain the implementation of KEPLER.
