### ISSUE TITLE
Failed to convert your checkpoint.

### ISSUE THREAD

**Issue by algoflow19** [THU-KEG/KEPLER#4]
**When I try:
python -m transformers.models.roberta.convert_roberta_original_pytorch_checkpoint_to_pytorch --roberta_checkpoint_path ./ --pytorch_dump_folder_path ./pytorch_model.bin**

**I got:**
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.7/site-packages/transformers/models/roberta/convert_roberta_original_pytorch_checkpoint_to_pytorch.py", line 181, in <module>
    args.roberta_checkpoint_path, args.pytorch_dump_folder_path, args.classification_head
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.7/site-packages/transformers/models/roberta/convert_roberta_original_pytorch_checkpoint_to_pytorch.py", line 58, in convert_roberta_checkpoint_to_pytorch
    roberta = FairseqRobertaModel.from_pretrained(roberta_checkpoint_path)
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.7/site-packages/fairseq/models/roberta/model.py", line 251, in from_pretrained
    **kwargs,
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.7/site-packages/fairseq/hub_utils.py", line 72, in from_pretrained
    arg_overrides=kwargs,
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 279, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 232, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 434, in _upgrade_state_dict
    registry.set_defaults(state["args"], tasks.TASK_REGISTRY[state["args"].task])
KeyError: 'MLMetKE'

**Clearly, the script can't handle it. Could you please provide the converted weight? Many Thanks.**

**Comment by Bakser** [comment]
It seems that the fairseq package you are using does not include the pretraining task in our work. Are you sure you are using the fairseq in this repo when running the script?

**Comment by algoflow19** [comment]
Thanks for your reply. I installed transformers==2.2.0 since the higher versions of it requires fairseq>=0.9, then I change wd to your main folder and run ‘pip install .’. I try **'python -m transformers.convert_roberta_original_pytorch_checkpoint_to_pytorch --roberta_checkpoint_path  ./roberta_base/   --pytorch_dump_folder_path output_path/'**. But I got:

loading archive file ./roberta_base
| dictionary: 50264 types
Traceback (most recent call last):
  File "convert.py", line 178, in <module>
    args.classification_head
  File "convert.py", line 46, in convert_roberta_checkpoint_to_pytorch
    roberta = FairseqRobertaModel.from_pretrained(roberta_checkpoint_path)
  File "/home/ubuntu/czr/KEPLER/KEPLER/fairseq/models/roberta/model.py", line 173, in from_pretrained
    **kwargs,
  File "/home/ubuntu/czr/KEPLER/KEPLER/fairseq/hub_utils.py", line 54, in from_pretrained
    arg_overrides=kwargs,
  File "/home/ubuntu/czr/KEPLER/KEPLER/fairseq/checkpoint_utils.py", line 173, in load_model_ensemble_and_task
    model = task.build_model(args)
  File "/home/ubuntu/czr/KEPLER/KEPLER/fairseq/tasks/MLMetKE.py", line 370, in build_model
    if self.args.double_ke:
AttributeError: 'Namespace' object has no attribute 'double_ke'

In ./roberta_base/, there are:
config.json  dict.txt  merges.txt  model.pt  tokenizer.json  vocab.json
The 'model.pt' is your checkpoint.
'output_path' is a created folder.

**Comment by Bakser** [comment]
Yes, looks like the conversion has been done successfully. It seems that the doubleKE option used for running with two different knowledge graphs triggers the problem. I will leave this issue open until fixing it later. Thanks for reporting!
